---
title: "ASPIRE_TablesandFigures"
author: "Dane Isenberg"
date: "2025-08-20"
output: html_document
---

```{r required packages, message=FALSE,warning=FALSE}
#packages
require(ggplot2)
require(tidyr)
require(dplyr)
require(parallel)
#output exludes figure 1 (embedded in text)
```

```{r illustration of performance of our method, table 1}
##table 1
#need to put in your file path!
df_sim1_aspire<-read.csv("/Users/File/aspiresimsv2_booterr8.csv")
df_t1_aspire<-df_sim1_aspire[,c("csl","csu","icc","Truth","EmpBias","MCError","VarAsymCL","CovCL","CovCLCorT")]

df_t1_aspire

#selection summary
apply(df_sim1_aspire[,10:15],2,range)

#errors 
cbind(df_sim1_aspire$AvgBootCLFail,df_sim1_aspire$AvgBootIndFail)
```

```{r comparing four estimators, figure 2}
## figure 2
#download and clean data
#need to put in your file path!
#results_l_f2<-readRDS("/Users/File/aspiref4homcomp4.rds")
results_f2<-do.call(cbind,results_l_f2)
df_f2<-as.data.frame(t(results_f2))
reps<-5000
df_f2<-data.frame(df_f2,set=rep(c("SmSelSmErr", "LarSelSmErr", "SmSelLarErr", "LarSelLarErr"), each=reps))

##selection and m.e. sizes by set
by(df_f2[,colnames(df_f2)[1:6]], df_f2$set, 
   function(x) colMeans(x, na.rm = TRUE))

## check convergence metrics 
df_f2_viable_proposed<-ifelse(abs(df_f2$Proposed_Estim)>1,NA,df_f2$Proposed_Estim)
df_f2_viable_proposed_hom<-ifelse(abs(df_f2$Proposed_Estim_Hom)>1,NA,df_f2$Proposed_Estim_Hom)
df_f2_viable_ipsw<-ifelse(abs(df_f2$IPSW_Estim)>1,NA,df_f2$IPSW_Estim)
df_f2_viable_ssonly<-ifelse(abs(df_f2$SSOnly_Estim)>1,NA,df_f2$SSOnly_Estim)

#table of convergence failures
table(is.na(df_f2_viable_proposed),df_f2$set)
table(is.na(df_f2_viable_proposed_hom),df_f2$set)
table(is.na(df_f2_viable_ipsw),df_f2$set)
table(is.na(df_f2_viable_ssonly),df_f2$set)

## values for output
df_f2$Proposed_Estim<-df_f2_viable_proposed
df_f2$Proposed_Estim_Hom<-df_f2_viable_proposed_hom
df_f2$IPSW_Estim<-df_f2_viable_ipsw
df_f2$SSOnly_Estim<-df_f2_viable_ssonly

#true ATE (should be same for four models under seed)
trueATE_vec<-rep(0,4)
for(j in 1:4){
  trueATE_vec[j]<-mean(results_l_f2[[j]]["TrueATE",])
}

## creating long table for ggplot output, only risk differences plotted
df_f2_long <- df_f2 %>%
  rename("Proposed SSW Estimator"="Proposed_Estim" , 
         "SSW Estimator Homogeneous"="Proposed_Estim_Hom",  
          "IPSW Estimator"="IPSW_Estim", 
         "SSO Estimator"="SSOnly_Estim") %>%
  pivot_longer(cols = c("Proposed SSW Estimator","SSW Estimator Homogeneous", "IPSW Estimator",
                        "SSO Estimator"),
               names_to = "Estimation_Type", 
               values_to = "Value") %>%
    mutate(trueATE = case_when(
    set == "SmSelSmErr" ~ trueATE_vec[1],
    set == "LarSelSmErr" ~trueATE_vec[2],
    set == "SmSelLarErr" ~ trueATE_vec[3],
    set == "LarSelLarErr" ~ trueATE_vec[4]))

sub_plot_names<-c(
        "SmSelSmErr" = "Small Classification Error & \n Small Selection Subset",
        "LarSelSmErr" = " Small Classification Error & \n Large Selection Subset",
        "SmSelLarErr" = "Large Classification Error & \n Small Selection Subset",
        "LarSelLarErr" = " Large Classification Error & \n Large Selection Subset")

#plot of estimators by different selection subset sizes and misclassifcation 
ggplot(df_f2_long, aes(x = Estimation_Type, y = Value, color=Estimation_Type, fill = Estimation_Type)) +  
  geom_boxplot(width = 0.5, size=.25, fill = "white", alpha = 0.7, outlier.shape=NA) +  #box  
  geom_hline(aes(yintercept = trueATE), linetype="dashed",color = "grey30", size = .25)+  
  facet_wrap(~ set, ncol = 2, labeller = as_labeller(sub_plot_names))+
  coord_cartesian(ylim = c(-0.5, 0.75)) +  
  # scale_fill_manual(labels = c("Proposed_Estim" = "Proposed SSW Estimator", 
  #                              "SSW Estimator Homogeneous"="Proposed_Estim_Hom",
  #                              "IPSW_Estim" = "IPSW Estimator",  
  #                              "SSOnly_Estim" = "SSO Estimator")) +  
  theme_minimal() +  
  theme(axis.text.x = element_blank(), 
        legend.position = "bottom",  
        legend.direction = "horizontal",  
        legend.title = element_blank()) + 
  labs(
    y = "ATE Estimate",
    x = NULL,
    color = "Estimation Method"
  )
```

```{r loading and exploring data and table 2}
##parent survey data set
#need to put in your file path!
df_aspire_names<-load("aspire_active_imp_parent_analysis_v2.RData")
df_aspire_parents<-get(df_aspire_names[1])

#arm = 1 nudge+, arm = 0 nudge
df_aspire_parents$Arm<-ifelse(df_aspire_parents$Arm==2,0,1)
#renumbering cluster id for simplicity
df_aspire_parents<-data.frame(df_aspire_parents,Id=as.numeric(factor(df_aspire_parents$clinic_name_label)))


#purported selection subset
sel_ind<-which(df_aspire_parents$responder==1)
df_aspire_select<-df_aspire_parents[sel_ind,]

#silver standard is reach outcome of original analysis 
df_aspire_parents$silver<-df_aspire_parents$reach
#defining gold answer 01 and 03 in survey 
#speak about firearm (01), offered gun-lock (03)
train_prog<-df_aspire_parents$par01
locks_prog<-df_aspire_parents$par03

#remove non 0,1 answers in questions and mark them as NA
gold_remove<-ifelse(train_prog==1 & locks_prog==1,1,ifelse(train_prog>1 | locks_prog>1,NA,0))
df_aspire_parents_remove<-df_aspire_parents
df_aspire_parents_remove<-data.frame(df_aspire_parents,gold=gold_remove)

#redefining selection subset as those which respond to both fully 
df_aspire_parents_remove$responder<-ifelse(is.na(gold_remove)==T,0,1)

#under each treatment 
#total visits
nrow(df_aspire_parents_remove)
#those under nudge+
length(which(df_aspire_parents_remove$Arm==1))
#those under nudge
length(which(df_aspire_parents_remove$Arm==0))

##classification tables, table 2 
#overall
table(gold=df_aspire_parents_remove$gold,silver=df_aspire_parents_remove$silver)
#by treatments
#nudge+
table(gold=df_aspire_parents_remove$gold[df_aspire_parents_remove$Arm==1],silver=df_aspire_parents_remove$silver[df_aspire_parents_remove$Arm==1])
#nudge 
table(gold=df_aspire_parents_remove$gold[df_aspire_parents_remove$Arm==0],silver=df_aspire_parents_remove$silver[df_aspire_parents_remove$Arm==0])
```

```{r ssw estimator for ASPIRE, table 3}
##our ssw estimator 
#variables for classification model
xlabs_name<-c("eth","gender_num","Clin_size")
clabs_name<-c("system_num") 

#sorted by id, complete case (6 drops, .01%)
#sorting is not necessary but used for bootstrap replication later
df_aspire_parents_rem_sorted<-df_aspire_parents_remove[order(df_aspire_parents_remove$Id),]
df_aspire_parents_rem_cc<-df_aspire_parents_rem_sorted[complete.cases(df_aspire_parents_rem_sorted[, c("silver",clabs_name,xlabs_name)]), ]

#ssw estimates  
mesbestim::mesb_estim(df=df_aspire_parents_rem_cc,xlabs=xlabs_name,clabs=clabs_name,trt="Arm",ssvar="silver",gsvar="gold",vald="responder",cl="Id",varprint=T)
```

```{r obtaining individual proportions for ssw estimator}
## checking all estimates directly
N<-nrow(df_aspire_parents_rem_cc)
df_aspire_parents_rem_cc_sel<-df_aspire_parents_rem_cc[which(df_aspire_parents_rem_cc$responder==1),]

#differentiation by x 
mefit<-glm(silver~gold*Arm+eth*Arm+gender_num*Arm+Clin_size*Arm+system_num,data=df_aspire_parents_rem_cc_sel,family="binomial")

new111<-data.frame(df_aspire_parents_rem_cc[,c(xlabs_name,clabs_name)],Arm=1,gold=1)
new101<-data.frame(df_aspire_parents_rem_cc[,c(xlabs_name,clabs_name)],Arm=1,gold=0)
new110<-data.frame(df_aspire_parents_rem_cc[,c(xlabs_name,clabs_name)],Arm=0,gold=1)
new100<-data.frame(df_aspire_parents_rem_cc[,c(xlabs_name,clabs_name)],Arm=0,gold=0)

p111hat<-predict(mefit,newdata=new111,type="response")
p101hat<-predict(mefit,newdata=new101,type="response")
p110hat<-predict(mefit,newdata=new110,type="response")
p100hat<-predict(mefit,newdata=new100,type="response")

phat<-mean(df_aspire_parents_rem_cc$Arm)

u1hat<-1/N*sum((df_aspire_parents_rem_cc$silver*df_aspire_parents_rem_cc$Arm-phat*p101hat)/
                 (phat*(p111hat-p101hat)))
u0hat<-1/N*sum((df_aspire_parents_rem_cc$silver*(1-df_aspire_parents_rem_cc$Arm)
                -(1-phat)*p100hat)/((1-phat)*(p110hat-p100hat)))

#all valid 
c("P1"=u1hat,"P0"=u0hat,"Estim"=u1hat-u0hat)
```
```{r sso estimator with non-par cluster boot, table 3}
#set for replication of boot
RNGkind("L'Ecuyer-CMRG")
set.seed(5)

##difference in means estimator, sso only
u1hat<-mean(df_aspire_parents_rem_sorted$silver[df_aspire_parents_rem_sorted$Arm==1])
u0hat<-mean(df_aspire_parents_rem_sorted$silver[df_aspire_parents_rem_sorted$Arm==0])
point_estim_ssonly<-u1hat-u0hat
names(point_estim_ssonly)<-"SS Only Estim"
#estimate of difference and components
c(P1=u1hat,P0=u0hat,point_estim_ssonly)

#cluster bootstrap interval for sso estimator, 1000 iters 
iters<-1000
dfog<-df_aspire_parents_rem_sorted
cl_boot_fun_ss_only<-function(iters){
  idval<-length(unique(dfog$Id))
  clustidv<-sample(unique(dfog$Id),idval,replace=T)
  dflist<-vector("list",idval)
  for(j in 1:idval){
    dflist[[j]]<-dfog[dfog$Id==clustidv[j],]
  }
  df<-do.call(rbind,dflist)
  ss_only_boot<-mean(df$silver[df$Arm==1])-mean(df$silver[df$Arm==0])
  return(ss_only_boot)}

ss_only_boot<-unlist(parallel::mclapply(1:iters,FUN=cl_boot_fun_ss_only,mc.cores=5))
var(ss_only_boot)
quantile(ss_only_boot,probs=c(0.025,0.975))
```


```{r ipsw estimator with non-par cluster boot, table 3}
#set for replication of boot
RNGkind("L'Ecuyer-CMRG")
set.seed(5)

##point estimator using ipsw 
dfog_gs<-df_aspire_parents_rem_cc

#renaming Arm as a, gold as y, and responders as v
colnames(dfog_gs)[c(6,90,79)]<-c("a","y","v")

N<-nrow(dfog_gs)
phat<-mean(dfog_gs$a)

#regressors for selection model, same as classification in ssw but without gold-standard outcome
xlabs_name<-c("eth","gender_num","Clin_size")
clabs_name<-c("system_num") 

#selection model 
p_sel_form<-paste("v","~",paste("a",paste(c(xlabs_name,clabs_name),                             collapse="+"),paste(paste("a",c(xlabs_name),sep="*"),collapse="+"),sep="+"),sep="")
p_sel_form<-as.formula(p_sel_form)
p_selfit<-glm(p_sel_form,family="binomial",data=dfog_gs)
fitted_v<-fitted.values(p_selfit)
select_v_ind<-which(dfog_gs$v==1)
fitted_v_select<-fitted_v[select_v_ind]
dfv<-dfog_gs[select_v_ind,]
u1hat<-sum((dfv$y*dfv$a)/(fitted_v_select*phat))/N
u0hat<-sum((dfv$y*(1-dfv$a))/(fitted_v_select*(1-phat)))/N
gs_est<-u1hat-u0hat
names(gs_est)<-"GS_Estim"

#estimate of difference and components
c(P1=u1hat,P0=u0hat,gs_est)

#cluster bootstrap interval for ipsw estimator, 1000 iters 
iters<-1000
cl_boot_fun_gs<-function(iters){
  idval<-length(unique(dfog_gs$Id))
  clustidv<-sample(unique(dfog_gs$Id),idval,replace=T)
  dflist<-vector("list",idval)
  for(j in 1:idval){
    dflist[[j]]<-dfog_gs[dfog_gs$Id==clustidv[j],]
  }
  df<-do.call(rbind,dflist)
  N<-nrow(df)
  phat<-mean(df$a)
  p_sel_form<-paste("v","~",paste("a",paste(c(xlabs_name,clabs_name),
                                            collapse="+"),paste(paste("a",c(xlabs_name),sep="*"),collapse="+"),sep="+"),sep="")
  p_sel_form<-as.formula(p_sel_form)
  p_selfit<-glm(p_sel_form,family="binomial",data=df)
  fitted_v<-fitted.values(p_selfit)
  select_v_ind<-which(df$v==1)
  fitted_v_select<-fitted_v[select_v_ind]
  dfv<-df[select_v_ind,]
  u1hat<-sum((dfv$y*dfv$a)/(fitted_v_select*phat))/N
  u0hat<-sum((dfv$y*(1-dfv$a))/(fitted_v_select*(1-phat)))/N
  gs_est<-u1hat-u0hat
  return(gs_est)}

boot_gs<-unlist(parallel::mclapply(1:iters,FUN=cl_boot_fun_gs,mc.cores=5))
var(boot_gs)
quantile(boot_gs,probs=c(0.025,0.975))
```

```{r comparing variance estimators cluster-robust sandwich, individual sandwich, non-par cluster boot, non-par indv boot, table s1}
##table s1
df_t1app_aspire<-df_sim1_aspire[,c("MCError","VarAsymCL","CovCLCorT","VarBootCl","CovBootCL","VarAsymInd","CovInd","VarBootInd","CovBootInd","AvgBootCLFail","AvgBootIndFail")]

df_t1app_aspire #includes failures
``` 

```{r adding clinician random effects in data generation,table s2}
##table s2
#need to put in your file path!
df_sim2app_aspire<-read.csv("/Users/File/aspiresimsv2bothwdoc8.csv")
df_t2app_aspire<-df_sim2app_aspire[,c("csl","csu","icc","Truth","EmpBias","MCError","VarAsymCL","CovCL","CovCLCorT")]

df_t2app_aspire
```

```{r adding classification model random effect in data generation, table s3}
##table s3
#need to put in your file path!
df_sim2app_aspire<-read.csv("/Users/File/aspiresimsv2bothwmenodoc8.csv")
df_t3app_aspire<-df_sim3app_aspire[,c("csl","csu","icc","Truth","EmpBias","MCError","VarAsymCL","CovCL","CovCLCorT")]

df_t3app_aspire
```

```{r classification types wrt clinic volume, figure s1}
library(ggpattern)
#naming data 
arm_labels <- c(
  "0" = "Nudge",
  "1" = "Nudge+"
)

#df for graphics
df_clinc_vol<-df_aspire_parents_remove

#creating classification column for figure, subset to validation
df_clinc_vol_aug <- df_clinc_vol %>%
  mutate(Classification = case_when(
    gold == silver ~ "Parent = Clinician",
    gold == 0 & silver == 1 ~ "Parent = 0, Clinician = 1",
    gold == 1 & silver == 0 ~ "Parent = 1, Clinician = 0")) %>%
  filter(!is.na(Classification))

#counts the number of those selected by clinic by each type of match
df_figa1 <- df_clinc_vol_aug %>%
  group_by(Arm, Id, Clin_size, Classification) %>%
  summarise(n = n(), .groups = "drop")

#creates Id as factor with levels that correspond to cluster size
df_figa1_plot <- df_figa1 %>%
  mutate(Id = factor(Id, levels = df_figa1 %>%
                       distinct(Id, Clin_size) %>%
                       arrange(Clin_size) %>%
                       pull(Id)))

#vertical line indicators
df_figa1_nudge <- df_figa1[df_figa1$Arm==0,]
df_figa1_nudge <- df_figa1_nudge %>%
  mutate(Id = factor(Id, levels = df_figa1_nudge %>%
                       distinct(Id, Clin_size) %>%
                       arrange(Clin_size) %>%
                       pull(Id)))

#vert lines volume cutoffs for nudge
v_1_n<-which(levels(df_figa1_nudge$Id)==unique(df_figa1_nudge[which(df_figa1_nudge$Clin_size==min(df_figa1_nudge[which(df_figa1_nudge$Clin_size>500),]$Clin_size)),]$Id))-.5
v_2_n<-which(levels(df_figa1_nudge$Id)==unique(df_figa1_nudge[which(df_figa1_nudge$Clin_size==min(df_figa1_nudge[which(df_figa1_nudge$Clin_size>1000),]$Clin_size)),]$Id))-.5
v_3_n<-which(levels(df_figa1_nudge$Id)==unique(df_figa1_nudge[which(df_figa1_nudge$Clin_size==min(df_figa1_nudge[which(df_figa1_nudge$Clin_size>2000),]$Clin_size)),]$Id))-.5

df_figa1_nudgeplus <- df_figa1[df_figa1$Arm==1,]
df_figa1_nudgeplus <- df_figa1_nudgeplus %>%
  mutate(Id = factor(Id, levels = df_figa1_nudgeplus %>%
                       distinct(Id, Clin_size) %>%
                       arrange(Clin_size) %>%
                       pull(Id)))

#vert lines volume cutoffs for nudge+
v_1_np<-which(levels(df_figa1_nudgeplus$Id)==unique(df_figa1_nudgeplus[which(df_figa1_nudgeplus$Clin_size==min(df_figa1_nudgeplus[which(df_figa1_nudgeplus$Clin_size>500),]$Clin_size)),]$Id))-.5
v_2_np<-which(levels(df_figa1_nudgeplus$Id)==unique(df_figa1_nudgeplus[which(df_figa1_nudgeplus$Clin_size==min(df_figa1_nudgeplus[which(df_figa1_nudgeplus$Clin_size>1000),]$Clin_size)),]$Id))-.5
v_3_np<-which(levels(df_figa1_nudgeplus$Id)==unique(df_figa1_nudgeplus[which(df_figa1_nudgeplus$Clin_size==min(df_figa1_nudgeplus[which(df_figa1_nudgeplus$Clin_size>2000),]$Clin_size)),]$Id))-.5

vline_figa1<-data.frame(Arm=rep(c(0,1),each=3),xintercept=c(v_1_n,v_2_n,v_3_n,
                                                            v_1_np,v_2_np,v_3_np),"Thresholds" = rep(c(">500",">1000",">2000"), 2))

levels(vline_figa1$Thresholds)<-c(">500",">1000",">2000")

#bar plot for classification types stratified by arm across clinic volumes 
ggplot(df_figa1_plot, aes(x = Id, y = n, fill = Classification)) +
  geom_bar(stat = "identity",position = "stack",color="black")+
  geom_vline(data=vline_figa1,aes(xintercept = xintercept, linetype = Thresholds), color = "grey35")+
  facet_wrap(~ Arm, ncol = 1, scales = "free_x",labeller = labeller(Arm = arm_labels)) +
  scale_fill_manual(values = c(
    "Parent = Clinician" = "#1b9e77", 
    "Parent = 0, Clinician = 1" = "#d95f02",
    "Parent = 1, Clinician = 0" = "#7570b3" 
  )
  , name="Classification Type") +
  scale_linetype_manual(values = c(
    ">500" = "solid",
    ">1000" = "dotted",
    ">2000" = "dashed"))+
  labs(
    x = "Pediatric Primary Care Clinics Ordered by Volume",
    y = "Number of Parent Responses",
    fill = "Cluster Volume",
    pattern = "Mismatch Type",
    #title = "Mismatch Distribution by Cluster and Treatment",
    linetype = "Volume Cutoffs"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_blank(),
    axis.line = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    strip.text = element_text(size = 11))+
  guides(
    fill = guide_legend(order = 1),
    linetype = guide_legend(order = 2)
  )
```

